In [1]:
# https://medium.com/@numanyilmaz61/numpy-in-50-cells-of-notebook-384f166163f6
import numpy as np
import sys

In [2]:
print('NumPy version:', np.__version__)
print('Python version',sys.version)

NumPy version: 1.21.5
Python version 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]


In [3]:
# Create one dimensional NumPy array
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
# Array of zeros
np.zeros(3)

array([0., 0., 0.])

In [5]:
# Array of 1s
np.ones(3)

array([1., 1., 1.])

In [6]:
# Array of 3 random integers between 1 and 10
np.random.randint(1,10, 3)

array([3, 5, 1])

In [7]:
# Create linearly spaced array
np.linspace(0, 10, 21 )

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [8]:
# Create 2-dimensional array
v = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [9]:
# For all rows change all elements at column with index 2 to be 5
v[:, 2] = 5

In [10]:
# Create 3x4 array values between 0 and 1
np.random.random((3,4))

array([[0.0708231 , 0.71667424, 0.76531196, 0.34013986],
       [0.42538768, 0.62535531, 0.32071845, 0.85097238],
       [0.22935275, 0.8516997 , 0.33900054, 0.19209093]])

In [11]:
a = np.array([1,2,3])
b = np.random.randint(0,10, (3,3))
print(a)
print(b)

[1 2 3]
[[0 3 5]
 [7 0 5]
 [9 9 0]]


In [12]:
# Adding new values into the the array
a = np.append(a, 4)
a

array([1, 2, 3, 4])

In [13]:
# Print the shape and dimension of arrays
print("Shape of a:", np.shape(a))
print("Shape of b:", np.shape(b))
print('Dimension of a:', np.ndim(a))
print('Dimension of b:', np.ndim(b))

Shape of a: (4,)
Shape of b: (3, 3)
Dimension of a: 1
Dimension of b: 2


In [14]:
# Number of elements in the arrays
print('Number of elements in a:', np.size(a))
print('Number of elements in b:', np.size(b))

Number of elements in a: 4
Number of elements in b: 9


In [15]:
# a is 1D array, we created before
a

array([1, 2, 3, 4])

In [16]:
# b is 2D array, we created before
b

array([[0, 3, 5],
       [7, 0, 5],
       [9, 9, 0]])

In [17]:
# Get the first element of a 
# These two print statements generate the same result
print(a[0])
print(a[-4])

1
1


In [18]:
# Get the last element of a 
# These two print statements generate the same result
print(a[-1]) 
print(a[3])

4
4


In [19]:
# Get the first row of b
# These two print statements generate the same result
print(b[0]) 
print(b[0,:])

[0 3 5]
[0 3 5]


In [20]:
# Get the second column of b
b[:,1]

array([3, 0, 9])

In [21]:
# To understand the fancy indexing better we will create two new arrays. 
x = np.array(['a', 'b', 'c'])
y = np.array([['d', 'e', 'f'], 
              ['g', 'h', 'k']])
print(x)
print(y)

['a' 'b' 'c']
[['d' 'e' 'f']
 ['g' 'h' 'k']]


In [22]:
# Fancy indexing on 1-D array
# Get the value of c in array x
ind = [2]
x[ind]

array(['c'], dtype='<U1')

In [23]:
# Fancy indexing on 2D array
# Get the values e, h in array y
ind2 = [[0,1],[1]]
y[ind2]

C:\Users\nikla\AppData\Local\Temp\ipykernel_29548\1536074053.py:4: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  y[ind2]


array(['e', 'h'], dtype='<U1')

In [24]:
# Create an array of integers from 1 to 10
X = np.arange(1, 11, dtype=int)
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Get the first two elements of X 
X[:2]

array([1, 2])

In [26]:
# Get the number 3,4 and 5 
X[2:5]

array([3, 4, 5])

In [27]:
# Get odd numbers 
X[::2]

array([1, 3, 5, 7, 9])

In [28]:
# Get even numbers
X[1::2]

array([ 2,  4,  6,  8, 10])

In [29]:
# Create 2-D array 
Y= np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# Get the first and second row
Y[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# Get the second and third column
Y[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [32]:
# Get the element of 5 and 6
Y[1,1:]

array([5, 6])

### numpy functions

In [33]:
# Mean of values in the X
np.mean(X)

5.5

In [34]:
# Get the 4th power of each element in X
np.power(X, 4)

array([    1,    16,    81,   256,   625,  1296,  2401,  4096,  6561,
       10000], dtype=int32)

In [35]:
# Trigonometric functions 
print(np.sin(X))
print(np.tan(X))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]


In [36]:
# (sinx)2 + (cosy)2 = 1 famous trigonometric equation
np.square(np.sin(X)) + np.square(np.cos(X))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
# array Y created before
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
# The same rules apply for 2-D arrays
np.multiply(Y, 2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [39]:
# split Y into 3 subarrays
np.split(Y, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [40]:
# Add 5 to each element of X
X + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
# Or 
np.add(X, 5)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
# Create new array Z 
Z = np.arange(3)[:, np.newaxis]
Z

array([[0],
       [1],
       [2]])

In [43]:
# Multiple Y and Z
np.multiply(Y, Z)

array([[ 0,  0,  0],
       [ 4,  5,  6],
       [14, 16, 18]])

In [44]:
# Create an array of 10 elements between 1 and 5
x = np.random.randint(1,5, 10)
x

array([2, 3, 4, 3, 3, 2, 3, 4, 4, 4])

In [45]:
# Create (3,3) size of array elements from 1 and 5
y = np.random.randint(1,5, (3,3))
y

array([[3, 1, 2],
       [3, 4, 3],
       [2, 2, 1]])

In [46]:
# Sort elements in array x
np.sort(x)

array([2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [47]:
# Sort values along the rows
np.sort(y, axis=0)

array([[2, 1, 1],
       [3, 2, 2],
       [3, 4, 3]])

In [48]:
# Sort values along the columns
np.sort(y, axis=1)

array([[1, 2, 3],
       [3, 3, 4],
       [1, 2, 2]])

In [52]:
print(x)
# == , !=, < , >, >=, <= operations on arrays
# This returns a Boolean
x > 3

[2 3 4 3 3 2 3 4 4 4]


array([False, False,  True, False, False, False, False,  True,  True,
        True])

In [50]:
# Use masking feature to get the values of comparisons
x[x>3]

array([4, 4, 4, 4])

In [51]:
# Another example 
x[(x <= 3) & ( x > 1 )]

array([2, 3, 3, 3, 2, 3])